project:
  type: website

website:
  title: "Dsan Mini Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: llmlog.qmd
        text: LLM Log
      - href: sources.qmd
        text: References

format:
  html:
    theme:
      - cosmo
      - brand
    bibliography: references.bib
    css: styles.css
    toc: true



